### ISSUE TITLE
Transition of popup doesn't work when uses this package.

### ISSUE THREAD

**Issue by devdreamsolution** [sanusart/react-dropdown-select#229]
This is my comment modal style.
```scss
.commentModal {
	background-color: var(--theme-chapter-toolbar-bg-color);
	position: fixed;
	top: 62px;
	right: 5px;
	width: 400px;
	bottom: 5px;
	box-shadow: -2px 1px 9px 0px rgb(85 85 85 / 13%);
	padding: 30px;
	border: 1px solid var(--theme-chapter-toolbar-border-color);
	border-radius: 5px;
	z-index: 3;
	transition: all 0.3s ease-in-out;

	&:global(.comment-modal-enter) {
		transform:translateX(100%);
	}

	&:global(.comment-modal-enter-active) {
		transform:translateX(0);
	}

	&:global(.comment-modal-exit) {
		transform:translateX(0);
	}

	&:global(.comment-modal-exit-active) {
		transform:translateX(100%);
	}
}
```

This is code to show comment modal using CSSTransition.
```js
<CSSTransition
    in={showCommentModal}
    timeout={300}
    classNames="comment-modal"
    unmountOnExit
    >
    <CommentModal
	    onCloseClick={() => setShowCommentModal(false)}
    />
</CSSTransition>
```

When the modal has react-dropdown-select, the screenshot is following.
The opening transition doesn't work now.
https://user-images.githubusercontent.com/54434088/159729723-02587d76-e6b0-44e5-a377-0b553c40ab29.mp4

But if I remove react-dropdown-select in modal, the transition works well.

https://user-images.githubusercontent.com/54434088/159730529-a7038db2-3bc1-4c2f-ac20-9d068663aa9f.mp4
